export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAIL = "APPOINTMENT_CREATE_FAIL";
export const APPOINTMENT_CREATE_RESET = "APPOINTMENT_CREATE_RESET";

//AllApptsList
export const ALL_APPTS_LIST_REQUEST = "ALL_APPTS_LIST_REQUEST";
export const ALL_APPTS_LIST_SUCCESS = "ALL_APPTS_LIST_SUCCESS";
export const ALL_APPTS_LIST_FAIL = "ALL_APPTS_LIST_FAIL";
export const ALL_APPTS_LIST_RESET = "ALL_APPTS_LIST_RESET";

//Details
export const APPOINTMENT_DETAILS_REQUEST = "APPOINTMENT_DETAILS_REQUEST";
export const APPOINTMENT_DETAILS_SUCCESS = "APPOINTMENT_DETAILS_SUCCESS";
export const APPOINTMENT_DETAILS_FAIL = "APPOINTMENT_DETAILS_FAIL";
export const APPOINTMENT_DETAILS_RESET = "APPOINTMENT_DETAILS_RESET";

//Update
export const APPOINTMENT_UPDATE_REQUEST = "APPOINTMENT_UPDATE_REQUEST";
export const APPOINTMENT_UPDATE_SUCCESS = "APPOINTMENT_UPDATE_SUCCESS";
export const APPOINTMENT_UPDATE_FAIL = "APPOINTMENT_UPDATE_FAIL";
export const APPOINTMENT_UPDATE_RESET = "APPOINTMENT_UPDATE_RESET";

//Doctors
export const DOCTOR_APPTS_LIST_REQUEST = "DOCTOR_APPTS_LIST_REQUEST";
export const DOCTOR_APPTS_LIST_SUCCESS = "DOCTOR_APPTS_LIST_SUCCESS";
export const DOCTOR_APPTS_LIST_FAIL = "DOCTOR_APPTS_LIST_FAIL";
export const DOCTOR_APPTS_LIST_RESET = "DOCTOR_APPTS_LIST_RESET";

//Patient
export const PATIENT_APPTS_LIST_REQUEST = "PATIENT_APPTS_LIST_REQUEST";
export const PATIENT_APPTS_LIST_SUCCESS = "PATIENT_APPTS_LIST_SUCCESS";
export const PATIENT_APPTS_LIST_FAIL = "PATIENT_APPTS_LIST_FAIL";
export const PATIENT_APPTS_LIST_RESET = "PATIENT_APPTS_LIST_RESET";

//delete
export const APPOINTMENT_DELETE_REQUEST = "APPOINTMENT_DELETE_REQUEST";
export const APPOINTMENT_DELETE_SUCCESS = "APPOINTMENT_DELETE_SUCCESS";
export const APPOINTMENT_DELETE_FAIL = "APPOINTMENT_DELETE_FAIL";
