export const DOCTOR_LOGIN_REQUEST = "DOCTOR_LOGIN_REQUEST";
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS";
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL";
export const DOCTOR_LOGOUT = "DOCTOR_LOGOUT";

export const DOCTOR_REGISTER_REQUEST = "DOCTOR_REGISTER_REQUEST";
export const DOCTOR_REGISTER_SUCCESS = "DOCTOR_REGISTER_SUCCESS";
export const DOCTOR_REGISTER_FAIL = "DOCTOR_REGISTER_FAIL";

export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL = "DOCTOR_LIST_FAIL";
export const DOCTOR_LIST_RESET = "DOCTOR_LIST_RESET";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";
export const DOCTOR_DETAILS_RESET = "DOCTOR_DETAILS_RESET";

export const DOCTOR_PROFILE_REQUEST = "DOCTOR_PROFILE_REQUEST";
export const DOCTOR_PROFILE_SUCCESS = "DOCTOR_PROFILE_SUCCESS";
export const DOCTOR_PROFILE_FAIL = "DOCTOR_PROFILE_FAIL";
export const DOCTOR_PROFILE_RESET = "DOCTOR_PROFILE_RESET";

export const DOCTOR_UPDATE_PROFILE_REQUEST = "DOCTOR_UPDATE_PROFILE_REQUEST";
export const DOCTOR_UPDATE_PROFILE_SUCCESS = "DOCTOR_UPDATE_PROFILE_SUCCESS";
export const DOCTOR_UPDATE_PROFILE_FAIL = "DOCTOR_UPDATE_PROFILE_FAIL";
export const DOCTOR_UPDATE_PROFILE_RESET = "DOCTOR_UPDATE_PROFILE_RESET";

export const DOCTOR_DELETE_REQUEST = "DOCTOR_DELETE_REQUEST";
export const DOCTOR_DELETE_SUCCESS = "DOCTOR_DELETE_SUCCESS";
export const DOCTOR_DELETE_FAIL = "DOCTOR_DELETE_FAIL";
export const DOCTOR_DELETE_RESET = "DOCTOR_DELETE_RESET";
