export const PATIENT_LOGIN_REQUEST = "PATIENT_LOGIN_REQUEST";
export const PATIENT_LOGIN_SUCCESS = "PATIENT_LOGIN_SUCCESS";
export const PATIENT_LOGIN_FAIL = "PATIENT_LOGIN_FAIL";
export const PATIENT_LOGOUT = "PATIENT_LOGOUT";

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";

export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";
export const PATIENT_LIST_RESET = "PATIENT_LIST_RESET";

export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";
export const PATIENT_DETAILS_RESET = "PATIENT_DETAILS_RESET";

export const PATIENT_PROFILE_REQUEST = "PATIENT_PROFILE_REQUEST";
export const PATIENT_PROFILE_SUCCESS = "PATIENT_PROFILE_SUCCESS";
export const PATIENT_PROFILE_FAIL = "PATIENT_PROFILE_FAIL";
export const PATIENT_PROFILE_RESET = "PATIENT_PROFILE_RESET";
