export const PATIENT_LOGIN_REQUEST = "PATIENT_LOGIN_REQUEST";
export const PATIENT_LOGIN_SUCCESS = "PATIENT_LOGIN_SUCCESS";
export const PATIENT_LOGIN_FAIL = "PATIENT_LOGIN_FAIL";
export const PATIENT_LOGOUT = "PATIENT_LOGOUT";

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";

export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";
export const PATIENT_LIST_RESET = "PATIENT_LIST_RESET";
